#!/bin/sh
# XR1710G: enable inet hardware flow offloading by default (IP24).
# The LuCI/RPC toggles set the same UCI options; make them the boot default.
uci set firewall.@defaults[0].flow_offloading='1'
uci set firewall.@defaults[0].flow_offloading_hw='1'
uci commit firewall
exit 0
